---
apiVersion: "v1"
kind: "List"
items:

  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: smackapi-deploy
    spec:
      replicas: 3
      template: 
        metadata:
          labels:
            app: smackapi
        spec:
          imagePullSecrets:
          - name: acrregistrykey
          containers:
          - name: smackapi
            image: "${apiACRImage}"
            ports:
            - containerPort: 8081

  - apiVersion: v1
    kind: Service
    metadata:
      name: smackapi
    spec:
      selector:
        app: smackapi
      type: ClusterIP  
      ports:
      - name: http
        port: 8081
        targetPort: 8081

  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: smackweb-deploy
    spec:
      replicas: 2
      template: 
        metadata:
          labels:
            app: smackweb
        spec:
          imagePullSecrets:
          - name: acrregistrykey
          containers:
          - name: smackweb
            image: "${webACRImage}"
            env:
            - name: API_SERVICE
              value: "smackapi.default.svc.cluster.local"
            - name: API_PORT
              value: "8081"
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBE_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBE_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            ports:
            - containerPort: 8080

  - apiVersion: v1
    kind: Service
    metadata:
      name: smackweb
    spec:
      selector:
        app: smackweb
      type: LoadBalancer
      ports:
      - name: http
        port: 8080
        targetPort: 8080