kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: smackapi-deploy
spec:
  replicas: 3
  template: 
    metadata:
      labels:
        app: smackapi
    spec:
      containers:
      - name: smackapi
        image: chzbrgr71/smackapi
        ports:
        - containerPort: 8081
---
kind: Service
apiVersion: v1
metadata:
  name: smackapi
spec:
  selector:
    app: smackapi
  type: ClusterIP  
  ports:
  - name: http
    port: 8081
    targetPort: 8081